config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: 'application#home'

  get 'points', to: 'health_centres#points'
  get 'hospital/:id', to: 'health_centres#hospital'
  get 'procedures/:id', to: 'health_centres#procedures'
  get 'specialties/:id', to: 'health_centres#specialties'
  get 'specialty_distance/:id', to: 'health_centres#specialty_distance'
  get 'procedures_specialties/:id', to: 'health_centres#procedures_specialties'

  get '/specialties_count', to: 'health_centres#specialties_count'
  get '/specialties_procedure_distance_average', to: 'health_centres#specialties_procedure_distance_average'
  get '/distances/:id', to: 'health_centres#distances'
  get '/rank_health_centres', to: 'health_centres#rank_health_centres'
  get '/distance_metric', to: 'health_centres#distance_metric'
  get '/distance_quartis/:id', to: 'health_centres#distance_quartis'
  get '/health_centre_count', to: 'health_centres#health_centre_count'
  get '/total_distance_average', to: 'health_centres#total_distance_average'

  resources :health_centres do
    get :procedures_setor_healthcentre, on: :collection
  end

  get 'estabelecimentos', to: 'health_centres#index'
  get 'dados-gerais', to: 'dashboard#index'
  get 'specialties', to: 'specialties#index'
  get 'busca', to: 'procedure#show'

  get '/procedure/health_centres', to: 'procedure#health_centres'
  get '/procedure/specialties', to: 'procedure#specialties'
  get 'procedure/proceduresInfo/:id', to: 'procedure#proceduresInfo'
  # get '/procedure/quartiles', to: 'procedure#proceduresQuartiles'
  get '/procedure/proceduresCompleteness', to: 'procedure#proceduresCompleteness'

  get '/about', to: 'application#about'
  get '/faq', to: 'application#faq'


  resources :procedure do
    get :healthCentresCnes, on: :collection
    get :proceduresPerMonth, on: :collection
    get :proceduresPerHealthCentre, on: :collection
    get :proceduresPerSpecialties, on: :collection
    get :proceduresDistance, on: :collection
    get :proceduresTotal, on: :collection
    get :download, on: :collection
    get :proceduresDistanceGroup,  on: :collection
    get :proceduresQuartiles, on: :collection
    get :proceduresMaxValues, on: :collection
    get :proceduresClusterPoints, on: :collection
    get :proceduresSetorCensitario, on: :collection 
    get :proceduresVariables, on: :collection
    get :proceduresCompleteness, on: :collection
    get :proceduresPop, on: :collection
    get :proceduresCid10Specific, on: :collection
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<%= stylesheet_link_tag "about.css" %>
<%= javascript_include_tag "about.js" %>

<div class="main">
  <div class="section section-1">
    <div class="content" data-aos="fade-up">
      <h1 class="header header-1">InternaSUS</h1>
      <p class="text">
        O Projeto InternaSUS é fruto de uma colaboração entre o <a href="http://interscity.org/">Projeto InterSCity</a>, sediado no IME-USP, e a <a href="http://www.prefeitura.sp.gov.br/cidade/secretarias/saude/">Secretaria Municipal da Saúde de São Paulo</a>.
        Nosso objetivo é utilizar técnicas avançadas de Ciência da Computação (Big Data, Visualização e Ciência de Dados) para fornecer ferramentas inovadoras para profissionais e gestores da saúde pública.
        Este é um projeto de software livre e assim, aberto a colaborações a fim de desenvolver avanços científicos na área de Informática e Big Data em Saúde.
        O InterSCity é financiado com recursos da FAPESP, CNPq e CAPES.
      <p>
    </div>
  </div>

  <div class="section section-2">
    <div class="content" data-aos="fade-up">
      <h2 class="header header-2">Desenvolvimento</h2>
      <p class="text">
        A plataforma de visualização de dados é um software livre licenciado sob a Mozilla Public License 2.0, que está sendo desenvolvida em Ruby on Rails e JavaScript e utilizando a API do OpenStreetMap.
        Seu repositório está disponível no <a href="https://gitlab.com/interscity/health-dashboard/health-smart-city">GitLab</a>.
      <p>
    </div>
  </div>

  <div class="section section-3">
    <div class="content" data-aos="fade-up">
      <h2 class="header header-3">Dados</h2>
      <p class="text">
        A plataforma apresenta os dados georreferenciados das internações custeadas pelo Sistema Único de Saúde, constantes no Sistema de Informação Hospitalar (SIH), fornecidos pela Secretaria Municipal de Saúde de São Paulo.
        A base de dados está anonimizada, não havendo informações sensíveis sobre os indivíduos e a localização dos domicílios foi generalizada para o centróide do setor censitário correspondente (territórios com população média de 600 habitantes, no município de São Paulo.
        <br><br>A ferramenta também apresenta(rá) informações demográficas, oriundas do Censo de 2010 realizado pelo IBGE e das projeções populacionais disponibilizadas pela Fundação SEADE,  estratificadas por sexo, faixa etária e raça/cor segundo as unidades territoriais administrativas da Prefeitura de São Paulo e da Secretaria Municipal da Saúde.
      <p>
    </div>
  </div>

  <div class="section section-4">
    <div class="content-presentation" data-aos="fade-up">
      <h2 class="header header-4">Utilização</h2>
      <iframe src="slideshow/presentation.html" height="100%" width="100%"></iframe>
    </div>
  </div>

  <div class="section section-membros">
    <div class="content-membros" data-aos="fade-up">
      <h3 class="header header-membros">Membros</h3>
        <div class="membros-container" id="membros-container">
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("baguiar.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Breno Aguiar</p>
              <p class="instituto">SMS/SP</p>
              <p class="descricao">Técnico na Gerência de Geoprocessamento e
              Informações Socioambientais (GISA) na Secretaria Municipal da Saúde de
              São Paulo (SMS).</p>
              <div class="media">
                <i class="fab fa-lg fa-facebook"></i>
                <i class="fab fa-lg fa-google-plus-square"></i>
                <i class="fab fa-lg fa-github-square"></i>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("mfailla.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Marcelo Failla</p>
              <p class="instituto">SMS/SP</p>
              <p class="descricao">Técnico na Gerência de Geoprocessamento e
              Informações Socioambientais (GISA) na Secretaria Municipal da Saúde de
              São Paulo (SMS).</p>
              <div class="media">
                <i class="fab fa-lg fa-facebook"></i>
                <i class="fab fa-lg fa-google-plus-square"></i>
                <i class="fab fa-lg fa-github-square"></i>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("fkon.png", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Prof. Fabio Kon</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Professor titular do Departamento de Ciência da Computação (DCC)
              do Instituto de Matemática e Estatística (IME) da Universidade de São Paulo (USP).<p>
              <div class="media">
                <a target="_blank" rel="noopener noreferrer" href="https://br.linkedin.com/in/fabiokon"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://twitter.com/fabiokon"><i class="fab fa-lg fa-twitter-square"></i></a>
                <a target="_blank" rel="noopener noreferrer" href="https://www.ime.usp.br/~kon/"><i class="fas fa-globe"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("kbraghetto.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Profª. Kelly Braghetto</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Professora do Departamento de Ciência da Computação (DCC)
              do Instituto de Matemática e Estatística (IME-USP)</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">kellyrb@ime.usp.br</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/kelly-rosa-braghetto-94b30344/"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://www.ime.usp.br/~kellyrb/"><i class="fas fa-globe"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("pmeirelles.png", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Prof. Paulo Meirelles</p>
              <p class="instituto">UNIFESP</p>
              <p class="descricao">Professor adjujnto do Departamento de Informática em Saúde
              da Unifersidade Federal de São Paulo (UNIFESP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">paulo.meirelles@unifesp.br</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/paulormm/"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://twitter.com/paulormm"><i class="fab fa-lg fa-twitter-square"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("dciriaco.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Débora Ciriaco</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Mestranda em Ciência da Computação do Instituto de
              Matemática e Estatística (IME) da Universidade de São Paulo (USP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">dciriaco@ime.usp.br</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/debora-lina-ciriaco-592a0a55/"><i class="fab fa-lg fa-linkedin"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("epinheiro.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Eduardo Pinheiro</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Estudante do Bacharelado em Ciência da Computação
                do Instituto de Matemática e Estatística (IME) da Universidade de São
                Paulo (USP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">eduardo.pinheiro482@hotmail.br</p>
                <a target="_blank" rel="noopener noreferrer" href="https://gitlab.com/eduardopinheiro482"><i class="fab fa-lg fa-git-square"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("ckodaira.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Camila Kodaira</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Estudante do Bacharelado em Ciência da Computação
                do Instituto de Matemática e Estatística (IME) da Universidade de São
                Paulo (USP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">naomicamila@hotmail.com</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/camila-kodaira-043635160/"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://gitlab.com/NaomiKodaira"><i class="fab fa-lg fa-git-square"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("gpereira.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Gabriely Pereira</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Estudante do Bacharelado em Ciência da Computação
                do Instituto de Matemática e Estatística (IME) da Universidade de São
                Paulo (USP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">gabriely.pereira@usp.br</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/gabriely-rangel-pereira-14114516a"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://gitlab.com/gabriely.pereira"><i class="fab fa-lg fa-git-square"></i></a>
              </div>
            </div>
          </div>
          <div class="membro">
            <div class="membro-img-frame">
              <%= image_tag("yhonda.jpg", :class => "membro-img") %>
            </div>
            <div class="membro-text">
              <p class="nome">Yurick Honda</p>
              <p class="instituto">IME/USP</p>
              <p class="descricao">Estudante do Bacharelado em Ciência da Computação
                do Instituto de Matemática e Estatística (IME) da Universidade de São
                Paulo (USP).</p>
              <div class="media">
                <i class="fas fa-lg fa-envelope-square" onclick="show_email(this)"></i>
                <p class="email">yurickyussuke@gmail.com</p>
                <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/yurick-honda-a32375161/"><i class="fab fa-lg fa-linkedin"></i>
                <a target="_blank" rel="noopener noreferrer" href="https://gitlab.com/yurickyh"><i class="fab fa-lg fa-git-square"></i></a>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<footer class="rodape">
  <div class="footer-container">
    <%= image_tag("sms-footer.png", :class => "footer-img") %>
    <ul class="footer-item">
      <li><strong>Secretaria Municipal da Saúde</strong></li>
      <li>R. General Jardim, 36 - Vila Buarque Telefone: 3397-2000</li>
    </ul>
    <ul class="footer-item">
      <li><strong>Contatos</strong></li>
      <li><i class="fa fa-envelope"></i> ouvidoriasaude@prefeitura.sp.gov.br</li>
      <li><i class="fa fa-phone"></i> 156</li>
    </ul>
  </div>
</footer>
<script>
  AOS.init();
</script>

app/views/application/faq.html.erb
<%= stylesheet_link_tag "faq.css" %>

<div class="box">
  <div class="type-block">
    <h1 class="title">Perguntas Frequentes</h1>
    <div class="type-row">
      <div class="type type-1 active" id="type1" onclick="changeFAQ1()">
        <div class="overlay" onclick="changeFAQ1()">
          <p>
            Início
          </p>
        </div>
      </div>
      <div class="type type-2" id="type2" onclick="changeFAQ2()">
        <div class="overlay" onclick="changeFAQ2()">
          <p>
            Busca Avançada
          </p>
        </div>
      </div>
      <div class="type type-3" id="type3" onclick="changeFAQ3()">
        <div class="overlay" onclick="changeFAQ3()">
          <p>
            Unidade Hospitalar
          </p>
        </div>
      </div>
    </div>
    <div class="triangle" id="triangle"></div>
  </div>

  <div class="viewer" id="viewer">
  <div class="question-container" id="question-container">
    <div class="question-block">
      <div class="side-bar" id="side-bar1">
        <p class="category" onclick="jump('inicio')">
          Início
        </p>
      </div>
      <div class="content">
        <div class="question-section">
          <span class="anchor" id="inicio"></span>
          <p class="question-header">
            Início
          </p>
          <p class="question">
            Como posso fazer pesquisas?
          </p>
          <p class="awnser">
            Na página inicial, na seção de serviços clique em Busca Avançada ou em Estabelecimentos.
            Em qualquer outra página na barra de navegação no topo da página clique na seção adequada.
            <!-- (Por favor alguém complete essa resposta) -->
          </p>
        </div>
      </div>
    </div>
    <div class="question-block">
      <div class="side-bar" id="side-bar2">
        <p class="category" onclick="jump('filtros')">
          Filtros
        </p>
        <p class="category" onclick="jump('mapa-busca')">
          Mapa
        </p>
        <p class="category" onclick="jump('opcoes')">
          Opções
        </p>
      </div>
      <div class="content">
        <div class="question-section">
          <span class="anchor" id="filtros"></span>
          <p class="question-header">
            Filtros
          </p>
          <p class="question">
            Como posso selecionar todas as opções de um filtro?
          </p>
          <p class="awnser">
            Quando uma opção do filtro é selecionada, há a opção de removê-la ou adicionar mais, apenas clicando sobre o campo novamente.
          </p>
          <p class="question">
            Como desfazer as seleções efetuadas?
          </p>
          <p class="awnser">
            No canto superior esquerdo do mapa presente na página de busca avançada, há um menu com as opções: Limpar, Imprimir, Dados Gerais e Download. A opção Limpar retira as seleções das opções.
          </p>
        </div>
        <div class="question-section">
          <span class="anchor" id="mapa-busca"></span>
          <p class="question-header">
            Mapa
          </p>
          <p class="question">
            O que é a opção Cluster?
          </p>
          <p class="awnser">
            Ao alterar o valor na opção Cluster e realizar a busca novamente por meio do botão Buscar, as internações hospitalares são reagrupadas (clusterizadas) de acordo com o novo valor de raio de convergência. Assim, com um menor valor de raio de convergência do cluster, as internações hospitalares tendem a ser mostradas de forma mais isolada, em um maior número de clusters.
          </p>
          <p class="question">
            O que é a opção Mapa de Calor?
          </p>
          <p class="awnser">
            Ao alterar o valor na opção Heatmap e realizar a busca novamente por meio do botão Buscar, as internações hospitalares são reagrupadas em uma nova mancha de calor seguindo o novo valor de raio de convergência. Assim, com um menor valor de raio de convergência do mapa de calor, as internações hospitalares tendem a aparecer em manchas que denotam uma menor quantidade de internações nesse raio.
          </p>
          <p class="question">
            O que significam os números dentro dos círculos distribuídos pelo mapa?
          </p>
          <p class="awnser">
            Os círculos (clusters) contêm um valor que representa a quantidade das internações hospitalares que foram agrupados naquele Cluster como resultado da pesquisa.
          </p>
        </div>
        <div class="question-section">
          <span class="anchor" id="opcoes"></span>
          <p class="question-header">
            Opções
          </p>
          <p class="question">
            O que será impresso quando eu clicar no botão Imprimir?
          </p>
          <p class="awnser">
            Ao clicar no botão Imprimir, o resultado da pesquisa feita será organizado em uma folha do tipo A4 e será impresso.
          </p>
          <p class="question">
            O que será baixado quando eu clicar no botão Download?
          </p>
          <p class="awnser">
            Ao clicar no botão Download, será preparado um arquivo , no formato CSV, com os procedimento resultantes da busca. Os campos desse arquivo seguem os padrões da SMS-SP e são preenchidos com dados de cada procedimento.
          </p>
        </div>
      </div>
    </div>
    <div class="question-block">
      <div class="side-bar" id="side-bar3">
        <p class="category" onclick="jump('estabel')">
          Estabelecimentos
        </p>
        <p class="category" onclick="jump('mapa-UH')">
          Mapa
        </p>
      </div>
      <div class="content">
        <div class="question-section">
          <span class="anchor" id="estabel"></span>
          <p class="question-header">
            Estabelecimentos
          </p>
          <p class="question">
            Como posso obter as informações da unidade hospitalar de interesse?
          </p>
          <p class="awnser">
            Na página de Estabelecimentos, ao selecionar um estabelecimento de saúde, obtém-se as informações referentes a ele no menu lateral à direita.
          </p>
          <p class="question">
            O que significa o número de leitos?
          </p>
          <p class="awnser">
            O número de leitos da página de Estabelecimentos representa a quantidade total de leitos do estabelecimento em questão.
          </p>
        </div>
        <div class="question-section">
          <span class="anchor" id="mapa-UH"></span>
          <p class="question-header">
            Mapa
          </p>
          <p class="question">
            O que significam os raios dos ícones da unidade hospitalar?
          </p>
          <p class="awnser">
            Os raios representam a região que delimita a quantidade de internações hospitalares , cujos pacientes residem em área próximas ao estabelecimento, presentes no quartil do determinado raio. Ao passar o mouse sobre as regiões coloridas é possível visualizar sua descrição.
          </p>
          <p class="question">
            O que significam os números dentro dos círculos distribuídos pelo mapa?
          </p>
          <p class="awnser">
            Os círculos (clusters) contêm um valor que representa a quantidade de internações hospitalares, realizados naquele determinado estabelecimento, que foram agrupados naquele Cluster.
          </p>
          <p class="question">
            Por quê os círculos aparecem em diferentes cores?
          </p>
          <p class="awnser">
            As cores são uma representação gráfica da quantidade de internações hospitalares representados naquele cluster.
          </p>
          <p class="question">
            O que signifca a área delimitada em azul quando passo o cursor do mouse em cima dos círculos?
          </p>
          <p class="awnser">
            A área azul delimita a região de todas as internações hospitalares contidas naquele cluster. Ao clicar no cluster é possível desfragmentá-lo em clusters menores.
          </p>
          <p class="question">
            Como posso ocultar os detalhes da unidade hospitalar para fazer uma nova busca?
          </p>
          <p class="awnser">
            No menu lateral à direita, há duas opções: Esconder Detalhes e Esconder Info.

            <ul>
              <li>Esconder Detalhes: fecha a busca do estabelecimento, o mesmo pode ser feito clicando no estabelecimento selecionado.</li>
              <li>Esconder Info: esconde as informações do estabelecimento selecionado, mantendo apenas os gráficos de especialidades.</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>



<script>
    $(document).ready(inicialize);
    $(window).on('resize', function(){
      if (currentPos === 1) {
        changeFAQ1();
      }
      else if (currentPos === 2) {
        changeFAQ2();
      }
      else {
        changeFAQ3();
      }
    });

    // window.onscroll = function() {sticky()};
</script>

app/views/application/home.html.erb
<%= stylesheet_link_tag "home.css" %>
<div class="barra-inst-full">
    <div class="barra-inst">
        <div class="barra-inst-block">
            <a href="http://www.capital.sp.gov.br/" class="barra-inst-link"><strong>PREFEITURA DE SÃO PAULO</strong></a>
        </div>
        <div class="barra-inst-block text-center">
            <a href="http://transparencia.prefeitura.sp.gov.br/acesso-a-informacao/Paginas/default.aspx" class="barra-inst-link"><strong>Acesso a Informação</strong> <%= image_tag("capital_acesso-informacao.png", :class => "capital-acesso-informacao", :alt => "Acesso a Informação") %></a>
        </div>
        <div class="barra-inst-block text-right">
            <a href="http://transparencia.prefeitura.sp.gov.br/Paginas/home.aspx" class="barra-inst-link">TRANSPARÊNCIA SÃO PAULO</a>
        </div>
    </div>
</div>

<div class="main">
  <div class="container">
    <header class="header">
      <%= image_tag("sms.jpg", :class => "logo-img") %>
      <h1 class="title">InternaSUS</h1>
    </header>
  </div>
</div>

<div class="slider" id="slideshow">
  <i class="fas fa-2x fa-chevron-left slider-btn left" onclick="plusDivs(1)"></i>
  <!-- O slider nao funciona com menos de 4 imagens -->
  <%= image_tag("slide1.jpg", :alt => "Imagem da vista de São Paulo a noite",:class => "slider-img active", :id => "slider1") %>
  <%= image_tag("slide2.jpg", :alt => "Imagem da vista da Avenida Paulista",:class => "slider-img left", :id => "slider2") %>
  <%= image_tag("slide3.jpg", :alt => "Imagem da vista de São Paulo de dia",:class => "slider-img right", :id => "slider3") %>
  <%= image_tag("slide4.png", :alt => "Imagem da Ponte Estaiada",:class => "slider-img", :id => "slider4") %>
  <i class="fas fa-2x fa-chevron-right slider-btn right" onclick="plusDivs(-1)"></i>
</div>

  <div class="main">
    <div class="data-row">
      <div class="data">
        <p class="data-num" id="procedure-data">0</p>
        <p class="data-label">Internações Hospitalares</p>
      </div>
      <div class="data">
        <p class="data-num" id="hospital-data">0</p>
        <p class="data-label">Estabelecimentos de Saúde</p>
      </div>
      <div class="data">
        <p class="data-num" id="spec-data">0</p>
        <p class="data-label">Especialidades</p>
      </div>
      <div class="data">
        <p class="data-num" id="desloc-data">0 km</p>
        <p class="data-label">Média de Deslocamento</p>
      </div>
    </div>
    <div class="container margin">
      <h2 class="section"> SERVIÇOS </h2>

      <div class="grid">
        <a href="<%= busca_path %>">
          <div class="item">
            <%= image_tag("buscaAvancada.png",:class => "item-img") %>
            <h3 class="item-title">Busca Avançada</h3>
            <p class="item-descript">
              Consulta de internações hospitalares, a partir de certos parâmetros de interesse, com a localização de ocorrência georreferenciada.
            </p>
          </div>
        </a>
        <%= link_to estabelecimentos_path, class: 'lnk', data: { turbolinks: false } do %>
          <div class="item">
            <%= image_tag("estabelecimento.png", :class => "item-img") %>
            <h3 class="item-title">Estabelecimentos</h3>
            <p class="item-descript">
              Informações gerais coletadas nos dados de internações hospitalares realizadas em estabelecimentos de saúde do município a partir de suas especialidades.
            </p>
          </div>
        <% end %>
        <a href="<%= dados_gerais_path %>">
          <div class="item">
            <%= image_tag("dadosGerais.png",:class => "item-img") %>
            <h3 class="item-title">Dados Gerais</h3>
            <p class="item-descript">
              Análise e resumo  de informações obtidas a partir dos dados de internações hospitalares, apresentadas de forma visual.
            </p>
          </div>
        </a>
        <a href="<%= about_path %>">
          <div class="item">
            <%= image_tag("about.png",:class => "item-img") %>
            <h3 class="item-title">Sobre o projeto</h3>
            <p class="item-descript">
              Conheça o projeto, informações tecnicas e a fonte dos dados, bem como a equipe do Universidade de São Paulo, Universidade Federal de São Paulo e Secretaria Municipal de Saúde que estão desenvolvendo o projeto.
            </p>
          </div>
        </a>
      </div>
</div>
<footer class="rodape">
  <div class="footer-container">
    <%= image_tag("sms-footer.png", :class => "footer-img") %>
    <ul class="footer-item">
      <li><strong>Secretaria Municipal da Saúde</strong></li>
      <li>R. General Jardim, 36 - Vila Buarque Telefone: 3397-2000</li>
    </ul>
    <ul class="footer-item">
      <li><strong>Contatos</strong></li>
      <li class="email"><i class="fa fa-envelope"></i> ouvidoriasaude@prefeitura.sp.gov.br</li>
      <li><i class="fa fa-phone"></i> 156</li>
    </ul>
  </div>
</footer>

<script>
  $(document).ready(showDivs);
  $(document).ready(getDataHomePage);

</script>